name: Build Flutter APK

on:
  push:
    branches:
      - main  # or change to your default branch (e.g., master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.2
      - run: |
          cd evn_calculator_app
          flutter pub get
      - run: |
          cd evn_calculator_app
          flutter test
      - run: |
          cd evn_calculator_app
          flutter build apk
      - run: |
          cd evn_calculator_app
          flutter build appbundle
