name: Build Flutter APK

on:
  push:
    branches:
      - main  # or change to your default branch (e.g., master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.2
      - run: |
          cd evn_calculator_app
          flutter pub get
          flutter build apk
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: evn_calculator_app/build/app/outputs/flutter-apk/app-release.apk
